---
kind: pipeline
type: docker
name: default
globals:
  - &docker_creds
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
steps:
  - name: prepare
    image: busybox
    commands:
      - mkdir -p /cache/${DRONE_REPO}/docker
    volumes:
      - name: cache
        path: /cache
  - name: env:staging
    image: nightfuryest/drone-plugin-secret-to-env
    settings:
      template: .deploy/.env.staging.template
      file: .env
      envs:
        - NODE_ENV
        - LOG_LEVEL
        - DATABASE_HOST
        - DATABASE_PORT
        - DATABASE_USERNAME
        - DATABASE_PASSWORD
        - DATABASE_DB_NAME
        - REDIS_URI
        - RABBITMQ_URI
      NODE_ENV:
        from_secret: NODE_ENV
      LOG_LEVEL:
        from_secret: LOG_LEVEL
      DATABASE_HOST:
        from_secret: DATABASE_HOST
      DATABASE_PORT:
        from_secret: DATABASE_PORT
      DATABASE_USERNAME:
        from_secret: DATABASE_USERNAME
      DATABASE_PASSWORD:
        from_secret: DATABASE_PASSWORD
      DATABASE_DB_NAME:
        from_secret: DATABASE_DB_NAME
      REDIS_URI:
        from_secret: REDIS_URI
      RABBITMQ_URI:
        from_secret: RABBITMQ_URI
    when:
      branch:
        - staging-*
  - name: Install Packages
    image: node:14-alpine
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder /yarn
      - yarn install --pure-lockfile --production=false
    volumes:
      - name: yarn
        path: /yarn
  - name: build:staging
    image: plugins/docker
    settings:
      registry: registry.fjob.com.vn
      repo: registry.fjob.com.vn/fjob-api
      tags:
        - latest
        - ${DRONE_COMMIT}
      create_repository: true
      use_cache: true
      <<: *docker_creds
    volumes:
      - name: docker
        path: /var/lib/docker
      - name: dhost
        path: /var/run/docker.sock
  - name: deploy:staging
    image: registry.fjob.com.vn/fjob-k8s:latest
    settings:
      secret_key:
        from_secret: GKE_SECRET_KEY
      user: drone-fjob-com-vn
      project_id: fjob-dev
    commands:
      - echo $PLUGIN_SECRET_KEY > gsa-key.json
      - gcloud auth activate-service-account $PLUGIN_USER@$PLUGIN_PROJECT_ID.iam.gserviceaccount.com --key-file=gsa-key.json
      - gcloud container clusters get-credentials fjob-staging --zone asia-southeast1-a --project fjob-dev
      - kubectl cluster-info
      - helm upgrade fjob-api-service /app/charts/common-api-service -n fjob -f /app/services/fjob-api-service/values.yaml --set image.tag=${DRONE_COMMIT}
volumes:
  - name: cache
    host:
      path: /var/cache
  - name: docker
    host:
      path: /var/cache/${DRONE_REPO}/docker
  - name: dhost
    host:
      path: /var/run/docker.sock
  - name: yarn
    host:
      path: /var/cache/${DRONE_REPO}/yarn

trigger:
  branch:
    - staging-*
  event:
    exclude:
      - pull_request
image_pull_secrets:
  - dockerconfig
