export const DefaultSetting = {
    // not need setting
    DEFAULT_CACHE_SETTING: 3600,
    // setting
    SUITABLE_THRESHOLD: 3600,//%
    DEFAULT_SEARCH_DISTANCE: 5000,//m
    MAX_OVERTIME_EXPIRED: 23,
    MAPPING_WORKING_TIME_PERCENT: 70,
}

export const SettingNames = {
    MAX_OVERTIME_EXPIRED: "MAX_OVERTIME_EXPIRED",
    MAPPING_WORKING_TIME_PERCENT: "MAPPING_WORKING_TIME_PERCENT",
    SUITABLE_THRESHOLD: "SUITABLE_THRESHOLD",
    DEFAULT_SEARCH_DISTANCE: "DEFAULT_SEARCH_DISTANCE",
}