export const ErrorCodes = {

    // General Error
    UNKNOWN: 9000,
    SYSTEM_GENERAL_ERROR: 9001,
    DATABASE_ERROR: 9002,
    INVALID_HEADERS: 9003,
    SYNTAXERROR: 9004,

    // Database
    DATABASE_CONNECTION_ERROR: 9100,
    INSERT_ERROR: 9101,
    UPDATE_ERROR: 9102,
    DELETE_ERROR: 9103,
    RECORD_NOT_FOUND: 9104,

    // Role
    FJOB_ROLE_NOT_SUPPORT: 1001,

    // Validate
    VALIDATION_INPUT_TYPE_ERROR: 1004,
    INVALID_USER_CODE: 1005,
    INVALID_PHONE_NUMBER: 1006,
    VALIDATION_INPUT_ERROR: 1003,

    //Pagination
    PAGE_OUT_OF_RANGE: 1010,
    SEARCH_ITEM_NOT_FOUND: 1011,

    // User
    USER_NOT_PERMIT: 2002,
    USER_NOT_EXIST: 2003,
    USER_CODE_ALREADY_EXISTS: 2004,
    USER_PHONE_NUMBER_ALREADY_EXISTS: 2005,
    USER_SALARY_EXPECT_INVALID: 2006,
    USER_SALARY_FROM_MUST_LESS_tO_SALARY: 2007,
    USER_NOT_EMPLOYEE: 2008,
    USER_NOT_EMPLOYER: 2009,
    PROVINCE_NOT_EXIST: 2012,
    DISTRICT_NOT_EXIST: 2013,
    USER_SCHEDULE_NOT_EXIT: 2010,
    WORKKING_TIME_TO_MUST_GREATER_FROM: 2011,
    REASON_DELETE_NOT_EXIST: 2014,
    NOTE_DELETE_IS_REQUIRED: 2015,
    NOTE_DELETE_NOT_APPLY_IN_THIS_REASON: 2016,
    WORKING_SHORT_TIME_TO_MUST_GREATER_FROM: 2017,
    REASON_REFUSE_IS_REQUIRED: 2018,
    REASON_REFUSE_NOT_EXIST: 2019,
    NOTE_REFUSE_NOT_APPLY_IN_THIS_REASON: 2020,
    NOTE_REFUSE_IS_REQUIRED: 2021,
    REASON_REFUSE_NOT_APPLY_IN_THIS_CASE: 2022,
    WORKKING_OF_JOB_MUST_FOLLOW_SHIFT_OR_INPUT_FROM_TO_TIME: 2023,
    SHIFT_NOT_EXITS: 2024,

    //CRUD Address
    ADDRESS_NOT_EXIST: 2002,
    DICTRICT_MUST_INPUT: 2003,
    LATITUDE_AND_LONGITUDE_MUST_INPUT: 2004,
    DISTRICT_NOT_IN_PROVINCE: 2005,

    // wallet & money
    WALLET_UPDATE_ERROR: 3001,
    WALLET_NOT_ENOUGH_MONEY: 3002,

    // Promotion
    ITEM_TYPE_NOT_APPLY_IN_THIS_PROMOTION: 3020,
    SERVICE_ID_DONATE_NOT_IN_THIS_PROMOTION: 3021,
    QUALITY_NOT_APPLY_IN_THIS_PROMOTION: 3022,
    QUANTITY_DONATE_NOT_APPLY_IN_THIS_PROMOTION: 3023,
    PROMOTION_PARAM_NOT_APPLY_IN_THIS_PROMOTION: 3024,

    // Buy Service
    BUY_SERVICE_FAILED_BESCAUSE_CAN_NOT_SAVE_TRANSACTION: 2100,
    BUY_SERVICE_USE_NOW_BUT_EXIST_SERVICE_NOT_USE_NOW: 2101,
    BUY_SERVICE_NOT_USE_NOW_BUT_EXIST_SERVICE_USE_NOW: 2102,

    // Crud Job post 5XXX, 6XXX
    JOB_INSERT_DATA_FAILED: 5000,
    JOB_UPDATE_DATA_FAILED: 5001,
    JOB_DELETE_DATA_FAILED: 5002,
    JOB_NOT_EXIST: 5003,
    JOB_PARTIME_NEED_TIME_FROM_TO: 5004,
    JOB_CAN_NOT_GET_DELETED_JOBS: 5005,
    JOB_EXP_REQUIRED_MUST_INPUT_EXPERIENCE_ID: 5006,
    JOB_WAS_HOT: 5007,
    JOB_CATEGORY_NOT_EXIST: 5008,
    EXP_TYPE_NOT_EXIST: 5009,
    PROF_SKILL_NOT_EXIST: 5010,
    JOB_APPLYING_ALREADY_EXIST: 5011,
    JOB_APPLYING_NOT_EXIST: 5012,
    EMPLOYER_NOTE_IS_NOT_NULL: 5013,
    EMPLOYER_NOT_PERMIT: 5014,
    HIRINGSTATUS_IS_REQUIRED: 5015,
    HIRINGSTATUS_UPDATE_VALID_IN_1_OR_2: 5016,
    USER_NOT_PERMIT_UPDATE_STATUS_AND_NOTE: 5017,
    KINDOFPERSON_VALID_IN_1_OR_2: 5018,
    HIRINGSTATUS_NEED_TO_CHANGE: 5019,
    SAVE_JOB_EXIST: 5020,
    SAVE_JOB_NOT_EXIST: 5028,
    JOB_CREATE_ONLY_HAVE_STATUS_DRAFF_OR_CENSORE: 5021,
    JOB_WAGE_MIN_MUST_LESS_THAN_WAGE_MAX: 5022,
    JOB_START_TIME_MUST_GREATER_THAN_CURRENT: 5023,
    JOB_FROM_AGE_MUST_LESS_THAN_TO_AGE: 5024,
    JOB_BENEFIT_HAVE_ITEM_NOT_EXIST: 5025,
    JOB_CATEGORY_HAVE_A_ITEM_NOT_EXIST: 5026,
    JOB_CATEGORY_EXP_REQUIRED_HAVE_A_ITEM_NOT_EXIST: 5027,
    JOB_YOU_MUST_BUY_SERVICE_AND_USE_POST_JOB_SERVICE: 5028,
    JOB_YOU_CAN_NOT_CHANGE_JOB_STATUS_WHEN_UPDATE: 5029,
    JOB_STATUS_MUST_DIFF_OLD_STATUS: 5030,
    JOB_NOT_PERMSSION_CHANGE_STATUS: 5031,
    JOB_MUST_USE_UGENT_SERVICE: 5032,
    JOB_CAN_NOT_UPDATE_URGENT_JOB: 5033,
    JOB_OLD_CAN_NOT_SET_HOT_OR_EXTEND: 5034,
    JOB_WORKING_TIME_INVALID: 5035,

    // Service and Promotion
    USER_ADDRESS_ALREADY_EXIST: 6000,
    PROMOTION_NOT_EXIST: 6001,
    SERVICE_IS_REQUIRED: 6002,
    SERVICE_NOT_EXIST: 6015,
    SERVICE_DONATE_NOT_EXIST: 6016,
    SERVICE_NAME_NOT_NULL: 6017,
    SERVICE_DESC_NOT_NULL: 6018,
    SERVICE_CODE_NOT_NULL: 6019,
    PROMOTION_PACKAGE_NOT_EXIST: 6003,
    PROMOTION_TYPE_NOT_EXIST: 6004,
    PROMOTION_NAME_IS_NOT_NULL: 6005,
    PROMOTION_DES_IS_NOT_NULL: 6006,
    PROMOTION_TYPE_CODE_IS_NOT_NULL: 6007,
    ITEM_TYPE_CODE_IS_REQUIRED: 6008,
    QUALITY_EXTRA_IS_REQUIRED: 6009,
    PROMOTION_TYPE_ALREADY_EXIST: 6010,
    ITEM_TYPE_NOT_EXIST: 6011,
    ITEM_TYPE_CODE_IS_USED: 6021,
    SERVICE_DONATE_IS_REQIRED: 6012,
    QUANTITY_DONATE_SERVICE_IS_REQIRED: 6013,
    QUANTITY_BUY_SERVICE_IS_REQUIRED: 6020,
    BASEPRICE_NOT_VALID: 6021,
    FROMTIME_NOT_VALID: 6022,
    TOTIME_NOT_VALID: 6022,
    FROMTIME_MUST_BE_SMALLER_TOTIME: 6023,
    BUYLIMIT_NOT_VALID: 6024,
    USENOW_VALID_IN_0_OR_1_OR_2: 6025,
    PROMOTION_PARAM_IS_REQUIRED: 6026,
    USE_NOW_NOT_EXIST: 6014,
    PROMOTION_PACKAGE_TO_LIMIT: 6015,

    SERVICE_HAVE_A_ITEM_NOT_EXIST: 6030,
    PROMOTION_HAVE_A_ITEM_NOT_EXIST: 6031,
    SERVICE_QUANTITY_HAVE_A_ITEM_EXCEEDING: 6032,
    ACCOUNT_IS_NOT_ENOUGH_TO_MAKE_TRANSACTION: 6033,
    SERVICE_QUANTITY_HAVE_A_ITEM_EXCEEDING_BUY_QUANTITY: 6034,
    SERVICE_BUY_HAVE_A_ITEM_USED_UP: 6035,
    SERVICE_BUY_HAVE_A_ITEM_NOT_EXIST: 6036,
    SERVICE_HAVE_A_ITEM_NOT_APPLY_FOR_USER: 6037,
    SERVICE_CAN_NOT_USE_SERVICE_OF_OTHER_PERSON: 6038,

    // Company
    COMPANY_NOT_EXIST: 7003,
    USER_NOT_COMPANY_EXIST: 7004,
    COMPANY_NAME_IS_NOT_NULL: 7005,
    COMPANY_DESC_IS_NOT_NULL: 7006,
    ISVERIFIED_VALID_IN_0_OR_1: 7007,
    INDUSTRYID_IS_VALID_NUMBER: 7008,
    USER_HAVE_NOT_THIS_ADDRESS: 7009,
    COMPANY_HAVE_NOT_THIS_ADDRESS: 7010,
    COMPANY_EE_CAN_NOT_CREATE: 7011,

    // Category
    FAVOURITE_CATEGORY_NOT_EXIST: 8003,
    USER_FAVOURITE_CATEGORY_ALREADY_EXIST: 8004,

    EXPERIENCE_NOT_EXIST: 8010,
    EDUCATION_LEVEL_NOT_EXIST: 8011,


    CANT_CALL_YOURSELF: 9001,
    CANT_CALL_USER_NOT_AVAILABLE: 9002,

    //Push Notification
    PUSH_NOTIFICATION_ERROR: 7100,
    SEGMENTS_AND_IDS_PRESENT: 7101,
    INVALID_PLAYER_ID: 7102,
    UNSUBSCRIBED_RECIPIENTS: 7103,
    UNSUPPORTED_PLATFORM: 7104,

    //Store purchase
    STORE_PURCHASE_ERROR: 9100,
    STORE_PURCHASE_INVALID_ITEM_ERROR: 9101
}
