export const PromotionType = {
    SALE_BUY_ITEM_GET_ITEM: "SALE_BUY_ITEM_GET_ITEM",
    SALE_PRICE: "SALE_PRICE",
    SALE_PERCENT_SERVICE: "SALE_PERCENT_PRICE",
    SALE_BUY_ITEM_GET_OTHER_ITEM: "SALE_BUY_ITEM_GET_OTHER_ITEM"
}